### ISSUE TITLE
Can't link Last.FM account to Polaris webui.

### ISSUE THREAD

**Issue by cr0wley** [agersant/polaris#223] opened 2024-10-22 00:56 UTC
![Screenshot_20241021_205550](https://github.com/user-attachments/assets/756ad156-6f1a-4366-a269-3294c822d31a)
![Screenshot_20241021_205555](https://github.com/user-attachments/assets/f046c6e9-b93d-4c8f-bc52-a088f5444d5c)

**Comment by agersant** [comment] 2024-10-22 01:51
Hello and sorry for the borked feature. Unfortunately, this will not get fixed in future releases. See this discussion here: https://github.com/agersant/polaris/issues/220

**Closed by agersant** 2024-10-22 01:51 UTC

**Comment by cr0wley** [comment] 2024-10-22 16:39
Is there any possibility of adding lines to a configuration using the last.fm api key/secret key? I've seen other software do that to handle last.fm integration.

**Comment by saecki** [comment] 2024-10-22 21:31
As discussed in the other issue, the problem is not on the interface side, but that the crate handling the last.fm integration isn't working anymore. So I doubt that using a configuration file will help here :)

**Comment by agersant** [comment] 2024-10-23 06:04
Small correction in case anyone is planning to fix it in a fork: I don't think the abandonment of the last.fm Rust crate is the source of the breakage. IIRC the account linking process does not relied on this crate. Everything else still stands though: account linking _is_ broken for unknown reasons, scrobble crate is unmaintained, and I no longer want avoidable ties to proprietary software.
