### ISSUE TITLE
Linux: library updates IO resources usage can be optimized

### ISSUE THREAD

**Issue by sashao** [agersant/polaris#159] opened 2021-11-10 10:05 UTC
![Screenshot 2021-11-10 at 10 29 13](https://user-images.githubusercontent.com/25319/141092283-fd5a16cf-31b8-4d40-89be-3655f7ea5f84.png)

I am using polaris for quite some time now without issues. (except manual updates on arch)
My music library consists mostly with mp3. In total it is about 40 GB on hard drive.

But when I left glances system monitoring tool overnight, it generated unpleasant report stating that that polaris periodically consumes a lot of IO bandwidth which slows my home server.

It would be great if in the feature we got smarter and greener update mechanism.

**Comment by sashao** [comment] 2021-11-10 10:09
Take a look on reports on the bottom of screenshot. 
I have syncthing also running on the same server. It is dealing with a lot more files, but never becomes a problem.

**Comment by lnicola** [comment] 2021-11-10 10:14
You should probably look into setting up the IO bandwidth controller (from cgroups) for polaris.

And as far as I can tell, those error messages mean that `polaris` and the others are waiting for the disk. So `polaris` and the VM get slowed down, not necessarily your whole system.

**Comment by agersant** [comment] 2021-11-10 10:21
Yeah this is most likely caused by the periodic scan. The work to switch to filesystem watches instead is tracked in #5. It's been a while since I looked at the state of cross-platform libs for this so hopefully the situation has improved now.

In the meantime, you can also reduce the frequency of the collection scan from `Settings -> Collection`  in the web client.

Closing this as a dupe of the issue linked above but feel free to continue the discussion if needed.

**Closed by agersant** 2021-11-10 10:21 UTC

**Comment by lnicola** [comment] 2021-11-10 10:33
> It's been a while since I looked at the state of cross-platform libs for this so hopefully the situation has improved now.

In 2019 we've stopped using `notify` in `rust-analyzer` stopped because of some relatively rare 100% CPU usage reports on MacOS. Of course it might be in a better shape now, but it's not something I can test.

**Comment by sashao** [comment] 2021-11-10 14:46
Thanks.
