### ISSUE TITLE
Problems authenticating

### ISSUE THREAD

**Issue by FKD13** [agersant/polaris#94] opened 2020-09-06 12:46 UTC
I am having trouble using the password my password manager generated for me.

The (old) password is the following: `#@2LDz*Exig4TqxwgD`

When I set this as my password I am unable to login and have to remove the database in order to be able to login again. All other passwords I tried (no special characters) seem to work like they should, so this looks like a bug to me. I don't have any errors in the logs to report.

**Comment by agersant** [comment] 2020-09-06 19:07
This looks a lot like https://github.com/agersant/polaris-web/issues/59

Can you reproduce this using the latest version of Polaris (0.12.4)?

**Comment by FKD13** [comment] 2020-09-19 19:34
I am using the latest docker build (https://github.com/ogarcia/docker-polaris) this should use the latest version.

**Comment by agersant** [comment] 2020-09-19 22:35
Thank you for confirming. Here is what I found:

- Cannot repro using latest from master
- Can repro using the `0.12.4` installer
- Version `0.12.4` does not contain the fix from agersant/polaris-web#59. This happened because the CI build of `polaris-web` containing this change failed for unrelated reasons. As a result, the `0.12.4` version did not include the fix.

I updated the release notes from `0.12.4` to reflect this, and the fix will be in `0.12.5` instead.

**Closed by agersant** 2020-09-19 22:35 UTC
Labels: bug
